In [84]:
# Numpy is a Python Library 
# Numpy is used for working with arrays
# Numpy stands for Numerical Python

import numpy as np # np is reference name (alias)

In [85]:
x = np.array(55)
print(x)
print(type(x))

55
<class 'numpy.ndarray'>


In [86]:
# The array object in Numpy is ndarray
# We can create Numpy ndarray object by using array() function

x1 = np.array([1,2,3,4,5])
print(x1)
print(type(x1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [87]:
print(np.__version__) #check the version

1.20.1


In [88]:
# To create an ndarray , we can pass a list , tuple or any other like object
# into the array() method and it will be converted into an ndarray

x2 = np.array((22,33,44))
print(x2)
print(type(x2))

[22 33 44]
<class 'numpy.ndarray'>


In [89]:
# Dimensions in array is one level of array depth
# Nested array are arrays that have arrays as their elements

# 0-D array -> these or scalars are the elements in an array.
# Each value in an arrray is 0-D array

x3 = np.array(45)
print("0-D Array")
print(x3)
print()
print()


# 1-D array are array that has 0-D array as its elements. 
# This is also Uni-Dimensional array . It is most Common Array

x4 = np.array([21,32,43])
print("1-D Array")
print(x4)
print()
print()


# 2-D array are array that has 1-D array as its elements.
# These are often used to represent the Matrix or @nd order Tensors 

x5 = np.array([[11,22,33],[34,56,78]])
print("2-D Array")
print(x5)
print()
print()


# 3-D array are array that has 2-D array as its elements.
# These are often used to represent the 3rd order Tensors

x6 = np.array([[[56,77,88],[54,12,32]],[[44,76,67],[98,76,54]]])
print("3-D Array")
print(x6)

0-D Array
45


1-D Array
[21 32 43]


2-D Array
[[11 22 33]
 [34 56 78]]


3-D Array
[[[56 77 88]
  [54 12 32]]

 [[44 76 67]
  [98 76 54]]]


In [90]:
# Numpy array Has ndim attribute that returns an integer 
# that tells us how many dimension the array have

print("0-D Array")
print(x3.ndim)
print()

print("1-D Array")
print(x4.ndim)
print()

print("2-D Array")
print(x5.ndim)
print()

print("3-D Array")
print(x6.ndim)
print()

0-D Array
0

1-D Array
1

2-D Array
2

3-D Array
3



In [91]:
# An array can have any number of dimesions
# when array is created , you can define the
# number of dimensions by using the ndmin arguments

x7 = np.array([5,8,9,5,4],ndmin=5)
print(x7)

[[[[[5 8 9 5 4]]]]]


In [92]:
# Access Array Elements
# Accesing Elemenst Through index

print(x1[2])
print(x1[1])
print(x1[0])

3
2
1


In [93]:
print(f"Sum of {x1} : {x1[0]+x1[1]+x1[2]+x1[3]+x1[4]}")

Sum of [1 2 3 4 5] : 15


In [94]:
# Access 2-D Array

print("2-D Array : ")
print(x5)
print()
print()


print("Second Row First Element : ",x5[1,0])
print("First Row Second Element : ",x5[0,1])

2-D Array : 
[[11 22 33]
 [34 56 78]]


Second Row First Element :  34
First Row Second Element :  22


In [95]:
# Access 3-D array

print("3-D Array : ")
print(x6)

print()
print()

print("Element x6[0,1,1]",x6[0,1,1])
print("Element x6[1,1,1]",x6[1,1,1])
print("element x6[1,1,2]",x6[1,1,2])

3-D Array : 
[[[56 77 88]
  [54 12 32]]

 [[44 76 67]
  [98 76 54]]]


Element x6[0,1,1] 12
Element x6[1,1,1] 76
element x6[1,1,2] 54


In [96]:
# Negative Indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print()
print("Dimension is : ",arr.ndim)
print()

print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Dimension is :  2

Last element from 2nd dim:  10


In [97]:
# Armstrong number is a number that is equal to the sum of cubes of its digits.
# Program To Check If the number is an Armstrong number or not

num = int(input("Enter Number : "))
sum = 0
temp = num
while temp>0:
    digit = temp%10
    sum = sum + digit**3
    temp = temp//10
if num==sum:
    print(f"{num} is Armstrong Number")
else:
    print(f"{num} is not Armstrong Number")

Enter Number : 89
89 is not Armstrong Number


In [98]:
def armstrong(number):
    sum1 = 0
    temp = number
    while temp>0:
        digit = temp%10
        sum1 = sum1 + digit**3
        temp = temp//10
    if number==sum1:
        print(f"{number} is Armstrong number")
    else:
        print(f"{number} is not Armstrong number")
        


user = ""
while user!='exit':
    user = input("Enter number to check no. is armstrong\
    or not or exit to leave : ")
    if user.isdigit():
        inp = int(user)
        armstrong(inp)
    else:
        print("Invalid Value")
            
        

Enter number to check no. is armstrong    or not or exit to leave : 407
407 is Armstrong number
Enter number to check no. is armstrong    or not or exit to leave : exit
Invalid Value


In [99]:
# Slicing Array
# Slicing in python means taking element from one given index to another given
# index. we pass slice instead of index like this [start:end].
# we can also define the step [start:end:step]
# if we don't pass start its considered as 0
# if we don't pass end it considered as length of array in that dimension
# if we don't pass step it considered 1

x7 = np.array([2,4,6,8,0,1])
print(x7)
print()
print("Dimension of Array : ",x7.ndim)
print("Type of Array : ",type(x7))
print("Slicing of x7[0:3] : ",x7[0:3])

[2 4 6 8 0 1]

Dimension of Array :  1
Type of Array :  <class 'numpy.ndarray'>
Slicing of x7[0:3] :  [2 4 6]


In [100]:
print("Not Give Start value x7[:4] : ",x7[:4])
print(f"Not Give End Value x7[4:] : {x7[4:]}")

# Thus it includes the start index but exclude the last index

Not Give Start value x7[:4] :  [2 4 6 8]
Not Give End Value x7[4:] : [0 1]


In [101]:
# Negative Slicing
# To use the minus operator to index from the end

print("Negative Indexing From x7[-3:-1] : ",x7[-3:-1])

Negative Indexing From x7[-3:-1] :  [8 0]


In [102]:
# Step is used to determine the step of slicing

print("Use of Step like this x7[0::2] : ",x7[0::2])

Use of Step like this x7[0::2] :  [2 6 0]


In [103]:
# Slicing in 2D Array

x8 = np.array([[2,3,4,5,6],[4,5,6,7,9]])
print("Dimension of x8 Array : ",x8.ndim)
print(f"Slicing in 2D Array x8[1,2:5] : {x8[1,2:5]}")

Dimension of x8 Array :  2
Slicing in 2D Array x8[1,2:5] : [6 7 9]


In [104]:
print("x8[0:2,2] : ",x8[0:2,2])

x8[0:2,2] :  [4 6]


In [105]:
print("x8[0:2,0:4] : ",x8[0:2,0:4])

x8[0:2,0:4] :  [[2 3 4 5]
 [4 5 6 7]]


In [106]:
# Data Types in Numpy refers to data types with one character i for integer u 
# for unsigned integer 

# Checking the Datatype of an array 
# The numpy array object has the property called dtype that returns the 
# datatype of an array

x9 = np.array([22,33,44,55,66])
print(f"Datatype of array {x9} is : {x9.dtype}")

Datatype of array [22 33 44 55 66] is : int32


In [107]:
x10 = np.array(['Apple','Banana','Papaya'])
print(f"Datatype of array {x10} is : {x10.dtype}")

Datatype of array ['Apple' 'Banana' 'Papaya'] is : <U6


In [108]:
# Creating Array With a Defined Data Type
# We use array() function to create arrays, this function can take an optional
# arguments: dtype that allows us to define the expected datatype 
# of an array element.

x11 = np.array([1,2,3,4,5] ,dtype='S')
print(f"Array is {x11}")
print(f"DataType of array {x11} is : {x11.dtype}")


Array is [b'1' b'2' b'3' b'4' b'5']
DataType of array [b'1' b'2' b'3' b'4' b'5'] is : |S1


In [109]:
x11 = np.array([1,2,3,4,5] ,dtype='i4')
print(f"Array is {x11}")
print(f"DataType of array {x11} is : {x11.dtype}")

Array is [1 2 3 4 5]
DataType of array [1 2 3 4 5] is : int32


In [110]:
# Converting Datatype of an existing arrays
# The Best way to make the change of the datatype of an exisitng array , is to 
# make the copy of the array of astype() method.
# The astype() method creates a copy of the array and allows to specify 
# datatype as a parameter 

x12 = np.array([66,77,88,99])
data = x12.astype('S')
print(x12)
print()
print(data)

[66 77 88 99]

[b'66' b'77' b'88' b'99']


In [111]:
x13 = np.array([1.3,4.3,3.3])
data1 = x13.astype('i')
print(x13)
print()
print(data1)

[1.3 4.3 3.3]

[1 4 3]


In [112]:
x14 = np.array([1.3,0,3.3])
data2 = x14.astype('bool')
print(x14)
print()
print(data2)

[1.3 0.  3.3]

[ True False  True]


In [113]:
# Shape of Array is the number of elements in each dimension
# Numpy array have an attribute shape that returns a tuple with each index 
# having the number of corresponding elements.

x19 = np.array([1,2,3,4,5])
print(f"Shape Dimension of {x19} is {x19.shape}")

Shape Dimension of [1 2 3 4 5] is (5,)


In [114]:
x20 = np.array([[1,2,3,4,5],[22,33,44,55,69]])
print(f"Shape Dimension of {x20} is {x20.shape}")

Shape Dimension of [[ 1  2  3  4  5]
 [22 33 44 55 69]] is (2, 5)


In [115]:
x21 = np.array([12,34,56,78],ndmin=5)
print(x21)
print(f"Shape of Array {x21} is {x21.shape}")

[[[[[12 34 56 78]]]]]
Shape of Array [[[[[12 34 56 78]]]]] is (1, 1, 1, 1, 4)


In [116]:
# Reshaping of an Array
# It means changing the shape of an array.
# By reshaping we can add or remove dimension or change 
# the no. of elements in each dimension

# Convert 1-D array in 2-D array
x22 = np.array([1,2,3,4,5,6,7,8,9,0,11,12])
x221 = x22.reshape(4,3)
# They have 4 array with 3 elements
print(f"By Using Reshape : {x221}")

By Using Reshape : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]]


In [117]:
# convert 2-D array in 3-D array

x23 = np.array([1,2,3,4,5,6,7,8,9,0,11,22])
x231 = x23.reshape(2,3,2)
print(f"2 Array that contain 3 Array with 2 Elements : {x231}")

2 Array that contain 3 Array with 2 Elements : [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 22]]]


In [118]:
# Return Copy or view
# check if return array is copy or view

x24 = np.array([1,2,3,4,5,6,7,8])
print(f"Check Return array is copy or view : {x24.reshape(2,4).base}")


Check Return array is copy or view : [1 2 3 4 5 6 7 8]


In [119]:
# Unknown Dimension
# You are allowed to have one "Unknown Dimension"

# Meaning that you do not have to specify an exact number for one of the

# dimension in the reshape method.
# pass -1 as the value, and Numpy will calculate this no. for you.

x25 = np.array([1,2,3,4,5,6,7,8])
x251 = x25.reshape(2,2,-1)
print(f"Unknown Dimension : {x251}")

# We cannot pass -1 to more than dimension

Unknown Dimension : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
# Flattening the Array
# Flattening the Array means converting multi-dimensional array into 1-D Array.
# We can reshape(-1) to do this

x26 = np.array([11,22,33,44,55,66,77])
x261 = x26.reshape(-1)
print(f"Reshape Array : {x261}")

Reshape Array : [11 22 33 44 55 66 77]


In [121]:
# Iterating Arrays
# Iterating means going through elements one by one
# As we deal multidimensional array in numpy we use for loop
# Iterating 1-D Array
x27 = np.array([1,2,3,4,5])
for i in x27:
    print(i)


1
2
3
4
5


In [122]:
# iterating 2-D Array
x27 = np.array([[1,2,3,4,5],[11,22,33,44,55]])
for i in x27:
    print(f"One-D Array : {i}")
    for j in i:
        print(f"Two-D Array : {j}")

One-D Array : [1 2 3 4 5]
Two-D Array : 1
Two-D Array : 2
Two-D Array : 3
Two-D Array : 4
Two-D Array : 5
One-D Array : [11 22 33 44 55]
Two-D Array : 11
Two-D Array : 22
Two-D Array : 33
Two-D Array : 44
Two-D Array : 55


In [123]:
# iterating 3-D Array
x27 = np.array([[[1,2,3,4,5],[11,22,33,44,55]],[[11,23,45,67,89],[111,
                                                            222,333,444,555]]])
for i in x27:
    print(f"One-D Array : {i}")
    for j in i:
        print(f"Two-D Array : {j}")
        for k in j:
            print(f"Three-D Array : {k}")

One-D Array : [[ 1  2  3  4  5]
 [11 22 33 44 55]]
Two-D Array : [1 2 3 4 5]
Three-D Array : 1
Three-D Array : 2
Three-D Array : 3
Three-D Array : 4
Three-D Array : 5
Two-D Array : [11 22 33 44 55]
Three-D Array : 11
Three-D Array : 22
Three-D Array : 33
Three-D Array : 44
Three-D Array : 55
One-D Array : [[ 11  23  45  67  89]
 [111 222 333 444 555]]
Two-D Array : [11 23 45 67 89]
Three-D Array : 11
Three-D Array : 23
Three-D Array : 45
Three-D Array : 67
Three-D Array : 89
Two-D Array : [111 222 333 444 555]
Three-D Array : 111
Three-D Array : 222
Three-D Array : 333
Three-D Array : 444
Three-D Array : 555


In [124]:
# The function nditer() is a helping function that can be used from very basic 
# to very advanced iterations. 

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [125]:
# Iterating array with different data types
# We can use op_dtypes argument and pass it is the expected datatypes of 
# elements while iterating


arr1 = np.array([1, 2, 3])

for x in np.nditer(arr1, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [126]:
# Iterating with different step size
# We can use filtering and followed by iteration
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr2[:, ::2]):
  print(x)

1
3
5
7


In [127]:
for x in arr2[:, ::2]:
  print(x)

[1 3]
[5 7]


In [128]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.
arr3 = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr3):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [129]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr4):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [130]:
# Joining means putting content of two or more array in a single array
# We use the concatenate method and pass the arguments
arr11 = np.array([1, 2, 3])

arr22 = np.array([4, 5, 6])

arr33 = np.concatenate((arr11, arr22))

print(arr33)

[1 2 3 4 5 6]


In [131]:
arr5 = np.array([[1, 2], [3, 4]])

arr6 = np.array([[5, 6], [7, 8]])

arr7 = np.concatenate((arr5, arr6), axis=1)

print(arr7)

[[1 2 5 6]
 [3 4 7 8]]


In [132]:
# Joining Arrays Using Stack Functions
# Stacking is same as concatenation, the only 
# difference is that stacking is done along a new axis.
arr8 = np.array([1, 2, 3])

arr9 = np.array([4, 5, 6])

arr10 = np.stack((arr8, arr9), axis=1)

print(arr10)

[[1 4]
 [2 5]
 [3 6]]


In [133]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.
arr11 = np.array([1, 2, 3])

arr12 = np.array([4, 5, 6])

arr13 = np.hstack((arr11, arr12))

print(arr13)

[1 2 3 4 5 6]


In [134]:
# Stacking Along Columns
# NumPy provides a helper function: vstack()  to stack along columns.
arr14 = np.array([1, 2, 3])

arr15 = np.array([4, 5, 6])

arr16 = np.vstack((arr14, arr15))

print(arr16)

[[1 2 3]
 [4 5 6]]


In [135]:
# Stacking Along Height (depth)
# NumPy provides a helper function: 
# dstack() to stack along height, which is the same as depth.

arr17 = np.array([1, 2, 3])

arr18 = np.array([4, 5, 6])

arr19 = np.dstack((arr17, arr18))

print(arr19)

[[[1 4]
  [2 5]
  [3 6]]]


In [136]:
# Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

# Joining merges multiple arrays into one and
# Splitting breaks one array into multiple.

# We use array_split() for splitting arrays, 
# we pass it the array we want to split and the number of splits.

arr20 = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr20, 3)

print(newarr)

# The return value is an array containing three arrays

[array([1, 2]), array([3, 4]), array([5, 6])]


In [137]:
# If the array has less elements than required,
# it will adjust from the end accordingly.
arr21 = np.array([1, 2, 3, 4, 5, 6])

newarr1 = np.array_split(arr21, 4)

print(newarr1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [138]:
# Split Into Arrays
# The return value of the array_split() 
# method is an array containing each of the split as an array.

# If you split an array into 3 arrays, you can access them from 
# the result just like any array element:

arr22 = np.array([1, 2, 3, 4, 5, 6])

newarr3 = np.array_split(arr22, 3)

print(newarr3[0])
print(newarr3[1])
print(newarr3[2])

[1 2]
[3 4]
[5 6]


In [139]:
# Use the same syntax when splitting 2-D arrays.

# Use the array_split() method, pass in the array you 
# want to split and the number of splits you want to do.

arr23 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr4 = np.array_split(arr23, 3)

print(newarr4)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [140]:
arr24 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],\
                  [13, 14, 15], [16, 17, 18]])

newarr5 = np.array_split(arr24, 3)

print(newarr5)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [141]:
arr25 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], \
                  [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr6 = np.array_split(arr25, 3, axis=1)

print(newarr6)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [142]:
# Use the hsplit() method to split the 2-D array into
# three 2-D arrays along rows.
arr27 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],\
                  [13, 14, 15], [16, 17, 18]])

newarr7 = np.hsplit(arr27, 3)

print(newarr7)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [143]:
# Searching Arrays
# You can search an array for a certain value, and return the indexes 
# that get a match.

# To search an array, use the where() method.

arr28 = np.array([1, 2, 3, 4, 5, 4, 4])

x28 = np.where(arr28 == 4)

print(x28)

# Find the indexes where the value is 4

# The example above will return a tuple: (array([3, 5, 6],)

# Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [144]:
arr29 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x29 = np.where(arr29%2 == 0)

print(x29)

# Find the indexes where the values are even

(array([1, 3, 5, 7], dtype=int64),)


In [145]:
arr30 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x30 = np.where(arr30%2 == 1)

print(x30)

# Find the indexes where the values are odd

(array([0, 2, 4, 6], dtype=int64),)


In [146]:
# Search Sorted
# There is a method called searchsorted() which performs a binary search
# in the array, and returns the index where the specified value would be
# inserted to maintain the search order.

# The searchsorted() method is assumed to be used on sorted arrays.

# Find the indexes where the value 7 should be inserted

arr31 = np.array([6, 8, 7, 9])

x31 = np.searchsorted(arr31, 7)

print(x31)

1


In [147]:
# Find the indexes where the value 7 should be inserted, starting from the
# right:

arr32 = np.array([6, 7, 8, 9])

x32 = np.searchsorted(arr32, 7, side='right')

print(x32)

2


In [148]:
# Find the indexes where the values 2, 4, and 6 should be inserted
arr33 = np.array([1, 3, 5, 7])

x33 = np.searchsorted(arr33, [2, 4, 6])

print(x33)

[1 2 3]


In [150]:
# Sorting Arrays
# Sorting means putting elements in an ordered sequence.

# Ordered sequence is any sequence that has an order corresponding 
# to elements, like numeric or alphabetical, ascending or descending.

# The NumPy ndarray object has a function called sort(), that will
# sort a specified array.

arr34 = np.array([3, 2, 0, 1])

print(np.sort(arr34))

# his method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [151]:
arr35 = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr35))

['apple' 'banana' 'cherry']


In [152]:
arr36 = np.array([True, False, True])

print(np.sort(arr36))

[False  True  True]


In [153]:
arr37 = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr37))

# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted

[[2 3 4]
 [0 1 5]]


In [154]:
# Filtering Arrays
# Getting some elements out of an existing array and creating a
# new array out of them is called filtering.

# In NumPy, you filter an array using a boolean index list.

# A boolean index list is a list of booleans corresponding to 
# indexes in the array.

# If the value at an index is True that element is contained in
# the filtered array, if the value at that index
# is False that element is excluded from the filtered array.

arr38 = np.array([41, 42, 43, 44])

x38 = [True, False, True, False]

newarr8 = arr38[x38]

print(newarr8)

[41 43]


In [155]:
# Creating the Filter Array
# In the example above we hard-coded the True and False values,
# but the common use 
# is to create a filter array based on conditions.

arr39 = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr39:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr9 = arr39[filter_arr]

print(filter_arr)
print(newarr9)

# Create a filter array that will return only values higher than 42:

[False, False, True, True]
[43 44]


In [156]:
# Create a filter array that will return only even 
# elements from the original array:

arr40 = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr1 = []

# go through each element in arr
for element in arr40:
  # if the element is completely divisble by 2, set the value to True, 
    # otherwise False
  if element % 2 == 0:
    filter_arr1.append(True)
  else:
    filter_arr1.append(False)

newarr10 = arr40[filter_arr1]

print(filter_arr1)
print(newarr10)

[False, True, False, True, False, True, False]
[2 4 6]


In [157]:
# Creating Filter Directly From Array
# The above example is quite a common task in NumPy and NumPy provides a nice
# way to tackle it.

# We can directly substitute the array instead of the iterable variable in our
# condition and it will work just as we expect it to.

# Create a filter array that will return only values higher than 42

arr41 = np.array([41, 42, 43, 44])

filter_arr2 = arr41 > 42

newarr11 = arr41[filter_arr2]

print(filter_arr2)
print(newarr11)

[False False  True  True]
[43 44]


In [158]:
# Create a filter array that will return only
# even elements from the original array

arr42 = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr3 = arr42 % 2 == 0

newarr12 = arr42[filter_arr3]

print(filter_arr3)
print(newarr12)

[False  True False  True False  True False]
[2 4 6]
